"""02_delete-lazy-db

Revision ID: 5e8e91ae644c
Revises: 1d4d04b9dbb2
Create Date: 2022-11-10 23:48:00.385599

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5e8e91ae644c'
down_revision = '1d4d04b9dbb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
